# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: hoote_dev
  pool: 5
  username: hoote
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: hoote_pro
  pool: 5
  username: hoote
  password:
